food(apple).
food(mango).
food(cauliflower).
food(rice).
food(lettuce).
likes(bob,carrot).
likes(bob,apple).
likes(joe,lettuce).
likes(mary,brocoli).
likes(bob,mary).
likes(joe,basketball).
likes(mary,baseball).
likes(jim,baseball).
color(sky,blue).
color(dirt,blue).
color(sky,brown).
color(grass,green).
color(brocoli,green).
color(lettuce,green).
color(apple,red).
color(tomato,red).
color(rose,red).
color(rice,white).
